name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.6.3
  - ipywidgets=7.7.2
  - seaborn=0.11.1
  - pandas=1.4.4
  - numpy=1.23.5
  - pip=20.3.3
  - pandas-profiling=3.3.0
  - pyarrow=2.0
  - pip:
      - wandb==0.13.7