name: train_val_test_split
channels:
  - conda-forge
  - defaults
dependencies:
  - pip=20.3.3
  - requests=2.28.2
  - mlflow=2.2.2
  - scikit-learn=1.2.2
  - pip:
      - wandb==0.13.7
      - git+https://github.com/sinemunal/build-ml-pipeline-for-short-term-rental-prices.git#egg=wandb-utils&subdirectory=components
