name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - mlflow=2.2.2
  - ipython=8.11.0
  - notebook=6.5.3
  - jupyterlab=3.6.3
  - cookiecutter=2.1.1
  - hydra-core=1.3.2
  - matplotlib=3.7.0
  - pandas=1.4.4
  - numpy=1.23.5
  - git=2.34.1
  - pip=20.3.3
  - pip:
      - wandb==0.13.7
